version: '3'
services:

  mrb-neo4j:
    image: neo4j:3.5
    restart: always
    ports:
    - "27474:7474"
    - "27687:7687"
    - "27473:7473"
    volumes:
    - /data/mrb_neo4j/data:/data
    - /data/mrb_neo4j/logs:/logs
    - /etc/timezone:/etc/timezone:ro
    environment:
      - NEO4J_AUTH=neo4j/dT9ymYwBsrzd
      - NEO4J_dbms_memory_heap_max__size=10G
      - NEO4J_dbms_memory_heap_initial__size=5G
      - NEO4J_dbms_memory_pagecache_size=10G
      - NEO4J_dbms_shell_enabled=true
      - NEO4J_dbms_allow__upgrade=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7474"]

  mr-base-api-restpluspy3:
    image: mr-base-api-restpluspy3:latest
    restart: always
    ports:
    - "8082:80"
    volumes:
    - /data/bgc:/data/bgc
    - /data/mrb_logs:/data/mrb_logs
    - /etc/timezone:/etc/timezone:ro
    environment:
      - NGINX_MAX_UPLOAD=750m
      - UWSGI_PROCESSES=20
      - UWSGI_THREADS=2
      - ENV=production
      - ACCESS=public
    depends_on:
      - mrb-neo4j
      - mr-base-api-cromwell
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]

  mr-base-api-cromwell:
    build: ./app/resources/workflow
    environment:
      - JAVA_OPTS=-Ddocker.hash-lookup.enabled=false -Dsystem.max-concurrent-workflows=1 -Dbackend.providers.Local.config.root=/data/cromwell-executions -Dworkflow-options.workflow-log-dir=/data/cromwell-workflow-logs
    ports:
    - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data:/data
      - /etc/timezone:/etc/timezone:ro
    command: ["server"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
