version: '3'
services:

  og-api:
    image: og-api:latest
    restart: always
    stdin_open: true
    tty: true
    ports:
    - "80:80"
    volumes:
    - /data/datasets:/data/igd
    - /data/api-logs:/data/mrb_logs
    - /data/ref/ld_files:/app/ld_files
    - /etc/localtime:/etc/timezone:ro
    environment:
      - FLASK_APP=main.py
      - ENV=production
      - ACCESS=public
      - POOL=api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/healthcheck"]

  og-profile:
    image: og-api:latest
    restart: always
    stdin_open: true
    tty: true
    ports:
    - "8080:80"
    volumes:
    - /data/datasets:/data/igd
    - /data/api-logs:/data/mrb_logs
    - /data/ref/ld_files:/app/ld_files
    - /etc/localtime:/etc/timezone:ro
    environment:
      - FLASK_APP=main.py
      - ENV=production
      - ACCESS=public
      - POOL=frontend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/healthcheck"]
