FROM python:3.11
EXPOSE 80

COPY ./app/requirements.txt /app/requirements.txt
RUN python -m pip install -r /app/requirements.txt

COPY ./vault /app/vault
COPY ./app /app

WORKDIR /app
RUN mkdir /data /data/igd /data/mrb_logs /data/tmp

RUN chmod +x /app/gunicorn.sh
CMD /app/gunicorn.sh
