version: '2'
services:
 #elasticsearch interface
   db:
    image: elasticsearch:6.2.4
    restart: always
    #comment out ports to lock down neo4j
    ports:
     - "19200:9200"
     - "19300:9300"
    environment:
     - node.data=false
     - cluster.name=mr-base
     #- xpack.security.enabled=false
     - ELASTIC_PASSWORD=mrbase
     - node.master=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
 #api
   api:
     build: .
     restart: always
     ports:
       - "8000:80"
     depends_on:
       - db
     tty: true
