version: '3'
services:

  mrb-neo4j:
    image: neo4j:3.5
    volumes:
    - /etc/timezone:/etc/timezone:ro
    environment:
      - NEO4J_AUTH=neo4j/dT9ymYwBsrzd
      - NEO4J_dbms_memory_heap_max__size=10G
      - NEO4J_dbms_memory_heap_initial__size=5G
      - NEO4J_dbms_memory_pagecache_size=10G
      - NEO4J_dbms_shell_enabled=true
      - NEO4J_dbms_allow__upgrade=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7474"]

  mr-base-api-v3-test:
    container_name: mr-base-api-v3-test
    image: mr-base-api-v3:latest
    volumes:
    - /etc/timezone:/etc/timezone:ro
    - /tmp:/app/populate_db/data:ro
    - /data/ref/ld_files:/app/ld_files:ro
    environment:
      - NGINX_MAX_UPLOAD=750m
      - UWSGI_PROCESSES=20
      - UWSGI_THREADS=2
      - ENV=production
      - ACCESS=private
      - FLASK_ENV=development
    depends_on:
      - mrb-neo4j
      - mr-base-api-cromwell
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]

  mr-base-api-cromwell:
    build: ./app/resources/workflow
    environment:
      - JAVA_OPTS=-Ddocker.hash-lookup.enabled=false -Dsystem.max-concurrent-workflows=1 -Dbackend.providers.Local.config.root=/data/cromwell-executions -Dworkflow-options.workflow-log-dir=/data/cromwell-workflow-logs -Ddatabase.profile="slick.jdbc.MySQLProfile$" -Ddatabase.db.driver="com.mysql.cj.jdbc.Driver" -Ddatabase.db.url="jdbc:mysql:mr-base-api-cromwell-mysql?rewriteBatchedStatements=true" -Ddatabase.db.user="root" -Ddatabase.db.password="kQzWHp2V" -Ddatabase.db.connectionTimeout=5000
    volumes:
      - /etc/timezone:/etc/timezone:ro
    command: ["server"]
    depends_on:
      - mr-base-api-cromwell-mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]

  mr-base-api-cromwell-mysql:
    image: mysql:8.0.2.1
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: kQzWHp2V
    volumes:
        - /etc/timezone:/etc/timezone:ro  
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=kQzWHp2V