FROM python:3.8

# install flask app
COPY ./app/requirements.txt /app/requirements.txt
WORKDIR /app
RUN pip install --upgrade pip && \
    pip install --no-cache-dir Cython && \
    pip install -r requirements.txt
