version: '3'
services:
  api:
    image: mrbase-api-image
    container_name: mrb-api
    volumes:
      - /var/www/api/mr-base-api/app:/app
    ports:
      - 8080:80
    depends_on:
      - database

  database:
    image: mysql:5.7
    container_name: mrb-mysql
    command: mysqld --user=root --verbose
    volumes:
      - $HOME/mysql/data2:/data
    ports:
      - "13306:3306"
    environment:
      MYSQL_DATABASE: "mrbase"
      MYSQL_USER: "mrbaseapp"
      MYSQL_PASSWORD: "M1st3rbase!"
      MYSQL_ROOT_PASSWORD: "g20XokfIrG0m"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
