---
title: "mrbase-api-test"
output: html_document
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE)
library(devtools)
```

Check how many studies are available
```{r available_outcomes}
get_ao <- function(){
  print ('Running available_outcomes')
  ao <- available_outcomes()
  print(dim(ao))
  #tail(ao)
  return(ao)
}
#get_ao()
```

```{r extract_instruments}
ei <- function(){
  print ('Running extract_instruments')
  start.time <- Sys.time()
  exposure_dat <- extract_instruments(outcomes=1,clump=FALSE)
  #exposure_dat <- extract_instruments(outcomes=89,clump=TRUE)
  #exposure_dat <- extract_instruments(outcomes=c(1,'UKB-a:95'),clump=TRUE)
  #exposure_dat <- extract_instruments(outcomes=c('1','2','UKB-a:21','UKB-a:22'),clump=TRUE)
  end.time <- Sys.time()
  time.taken <- end.time - start.time
  print (time.taken)
  print(dim(exposure_dat))
  return(exposure_dat)
}
#ei()
```

```{r extract_outcome_data}
eo <- function(exposure_dat){
  print ('Running extract_outcome_data')
  start.time <- Sys.time()
  #outcome_dat <- extract_outcome_data(exposure_dat$SNP, c('1','2','5','6','17','18','965','966','996','997','1090','UKB-a:96','UKB-a:1','UKB-a:2'))
  outcome_dat <- extract_outcome_data(exposure_dat$SNP, c('17','18','UKB-a:96','UKB-a:1','UKB-a:2'))
  #outcome_dat <- extract_outcome_data(exposure_dat$SNP, '7')
  #outcome_dat <- extract_outcome_data(outcomes=c('1','2','5','6'),snps=c('rs2825569','rs9821657','rs1919329'),splitsize=50000)
  print(dim(outcome_dat))
  end.time <- Sys.time()
  time.taken <- end.time - start.time
  print (time.taken)
  return(outcome_dat)
  
}
#eo(exposure_dat)
```

```{r harmonise}
harmonise <- function(exposure_dat, outcome_dat){
  print('harmonising...')
  dat <- harmonise_data(exposure_dat, outcome_dat)
  return(dat)
}
```

```{r perform MR}
do_mr <- function(dat){
  print('doing MR...')
  dat <- mr(dat)
}
```

```{r do-test}
do_test <- function(){
  start.time <- Sys.time()
  get_ao()
  exposure_data = ei()
  outcome_data = eo(exposure_data)
  end.time <- Sys.time()
  time.taken1 <- end.time - start.time
  dat = harmonise(exposure_data,outcome_data)
  mr_res = do_mr(dat)
  print (head(mr_res))
  end.time <- Sys.time()
  time.taken2 <- end.time - start.time
  print (time.taken1)
  print (time.taken2)
  return(mr_res)
}
```

```{r locall-api, include=FALSE}
load_all('~/projects/TwoSampleMR_edit/')
#install_github("MRCIEU/TwoSampleMR")
#library(TwoSampleMR)
toggle_dev('localtest')
mr_res=do_test()
```

```{r original-api, include=FALSE}
load_all('~/projects/TwoSampleMR/')
toggle_dev('release')
mr_res=do_test()
```

```{r es-api, include=FALSE}
#load_all('~/projects/TwoSampleMR_edit/')
install_github("MRCIEU/TwoSampleMR")
library(TwoSampleMR)
toggle_dev('elastic')
mr_res=do_test()
```

```{r bmc_chd}
#install_github("MRCIEU/TwoSampleMR",force = TRUE)
library(TwoSampleMR)
t1 <- Sys.time()
toggle_dev("release")
e1 <- extract_instruments(2)
o1 <- extract_outcome_data(e1$SNP, 7)
d1 <- harmonise_data(e1, o1)
m1 <- mr(d1)
t2 <- Sys.time()

toggle_dev("elastic")
e2 <- extract_instruments(2)
o2 <- extract_outcome_data(e2$SNP, 7)
d2 <- harmonise_data(e2, o2)
m2 <- mr(d2)
t3 <- Sys.time()
time.taken1 <- t2 - t1
time.taken2 <- t3 - t2
print (time.taken1)
print (time.taken2)
```

```{r multivariable_MR, eval=FALSE}
id_exposure <- c(299, 300, 302)
id_outcome <- 7
exposure_dat <- mv_extract_exposures(id_exposure)
outcome_dat <- extract_outcome_data(exposure_dat$SNP, id_outcome)
```